server:
  port: 8081
---
spring:
  application:
    name: UserService
  config:
    import: "optional:configserver:http://192.168.0.112:8085"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
# using remote configuration via configrepo
# eureka:
#   instance:
#     refer-ip-address: true
#   client:
#     fetch-registry: true
#     register-with-eureka: true
#     service-url:
#       defaultZone: http://localhost:8761/eureka